### PR TITLE
Update timeago_functions.php

### PR DESCRIPTION
**Pull request by sakkiotto**
for translate language in first post user

### CODE REVIEW

**Comment by MuhClaren** [comment]
Thanks for that! Sorry I missed it, I was really busy that day!

**Comment by sakkiotto** [comment]
italian language.. :)

2015-08-14 9:58 GMT+02:00 MuhClaren notifications@github.com:

**Comment by MuhClaren** [comment]
Please send a pull request with Italian translation. Thank you!

**Comment by sakkiotto** [comment]
I do not know how to use github .. I'm not a coder

lol :)

2015-08-14 17:36 GMT+02:00 MuhClaren notifications@github.com:

**Pull request merged**
